wucdbm_menu_builder_menu_list:
    path:        /list
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:list }

wucdbm_menu_builder_menu_create:
    path:        /create
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:create }

wucdbm_menu_builder_menu_list_row_refresh:
    path:        /{id}/list/refresh
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:refreshListRow }

wucdbm_menu_builder_menu_edit:
    path:        /{id}/edit
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:edit }

wucdbm_menu_builder_menu_name_update:
    path:        /{id}/update/name
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:updateName }

wucdbm_menu_builder_menu_preview:
    path:        /{id}/preview
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:preview }

wucdbm_menu_builder_menu_make_system:
    path:        /{id}/make/system
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:makeSystem }

wucdbm_menu_builder_menu_make_public:
    path:        /{id}/make/public
    defaults:    { _controller: WucdbmMenuBuilderBundle:Menu:makePublic }
